from typing import Any

class SimpleCookieJar:
    jar: Any = ...
    def __init__(self) -> None: ...
    def add(self, set_cookie: Any) -> None: ...
    def set(self, set_cookie: Any) -> None: ...
    def get(self, host: Any): ...
