from typing import Any, Optional

class WebSocketException(Exception): ...
class WebSocketProtocolException(WebSocketException): ...
class WebSocketPayloadException(WebSocketException): ...
class WebSocketConnectionClosedException(WebSocketException): ...
class WebSocketTimeoutException(WebSocketException): ...
class WebSocketProxyException(WebSocketException): ...

class WebSocketBadStatusException(WebSocketException):
    status_code: Any = ...
    resp_headers: Any = ...
    def __init__(self, message: Any, status_code: Any, status_message: Optional[Any] = ..., resp_headers: Optional[Any] = ...) -> None: ...

class WebSocketAddressException(WebSocketException): ...
