from ._exceptions import *
from ._http import *
from ._logging import *
from ._socket import *
from typing import Any

SUPPORTED_REDIRECT_STATUSES: Any

class handshake_response:
    status: Any = ...
    headers: Any = ...
    subprotocol: Any = ...
    def __init__(self, status: Any, headers: Any, subprotocol: Any) -> None: ...

def handshake(sock: Any, url: Any, hostname: Any, port: Any, resource: Any, **options: Any): ...
