import ssl as ssl
from ssl import SSLError as SSLError, SSLWantReadError as SSLWantReadError, SSLWantWriteError as SSLWantWriteError

HAVE_SSL: bool

# class SSLError(Exception): ...
# class SSLWantReadError(Exception): ...
# class SSLWantWriteError(Exception): ...
