from typing import Any, Optional

def parse_url(url: Any): ...
def get_proxy_info(hostname: Any, is_secure: Any, proxy_host: Optional[Any] = ..., proxy_port: int = ..., proxy_auth: Optional[Any] = ..., no_proxy: Optional[Any] = ..., proxy_type: str = ...): ...
