from typing import Any

class NoLock:
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

def validate_utf8(utfbytes: Any): ...
def extract_err_message(exception: Any): ...
def extract_error_code(exception: Any): ...
